services:
  - type: web
    name: alabanza-manager-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: USERNAME_DOMAIN
        value: alabanza-manager.com
      - key: FRONTEND_ORIGIN
        value: https://alabanza-b1296.web.app
